<?php
session_start();

require_once 'database/connect.php';
include 'includes/header.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: index.php");
    exit();
}


// Define moods with their emojis and 50 quotes each
$moods = [
    'sad' => [
        'emoji' => '😢',
        'name' => 'Sad',
        'color' => '#6B7FD7',
        'quotes' => [
            "Every storm runs out of rain. Better days are coming! 🌈",
            "Your feelings are valid, but they don't define you. You're stronger than this! 💪",
            "It's okay to not be okay. Tomorrow is a new opportunity! 🌅",
            "This too shall pass. You've overcome challenges before! ✨",
            "Your current situation is not your final destination. Keep going! 🚀",
            "Tears are words the heart can't express. Let them flow, then rise again! 💧",
            "Even the darkest night will end and the sun will rise! 🌄",
            "You are braver than you believe and stronger than you seem! 🦁",
            "Pain is temporary, but the lessons learned are forever! 📚",
            "Your breakthrough is just beyond this breakdown! 🌟",
            "Sadness is a part of life, not the end of it! 🌸",
            "Every setback is a setup for a comeback! 💫",
            "You've survived every bad day so far. You're doing amazing! 🎯",
            "The sun is always shining above the clouds! ☀️",
            "Your story isn't over yet. Keep turning the pages! 📖",
            "Healing takes time, and that's perfectly okay! ⏰",
            "You are loved, valued, and needed in this world! 💝",
            "Behind every cloud is a silver lining waiting to shine! ⛅",
            "Your tears water the seeds of your future strength! 🌱",
            "It's okay to rest, but don't give up! 🛋️",
            "You matter more than you know right now! 🌺",
            "This feeling is temporary, your resilience is permanent! 🏔️",
            "You're allowed to scream, cry, and then rise! 🦅",
            "Better chapters are being written for you! ✍️",
            "Your heart knows how to heal itself! 💚",
            "Even broken crayons still color! 🖍️",
            "You are enough, even on your hardest days! 🌼",
            "The comeback is always stronger than the setback! 💪",
            "Your feelings matter and so do you! 🎈",
            "Storms make trees take deeper roots! 🌳",
            "You're not alone in this journey! 🤝",
            "Tomorrow holds new possibilities for you! 🌅",
            "Your courage is greater than your sadness! 🛡️",
            "Every ending is a new beginning in disguise! 🌙",
            "You have survived 100% of your toughest days! 📊",
            "Let yourself feel, then let yourself heal! 🩹",
            "Your presence on earth makes a difference! 🌍",
            "The best views come after the hardest climbs! 🏔️",
            "You're stronger than the sadness you feel! 💎",
            "This chapter is tough, but you're tougher! 📕",
            "Your smile will return, brighter than before! 😊",
            "Rock bottom is solid ground to rebuild on! 🏗️",
            "You are worthy of happiness and peace! 🕊️",
            "Your emotions make you human and beautiful! 🎨",
            "Stars can't shine without darkness! ⭐",
            "You have the power to write a better tomorrow! ✨",
            "Your heart is healing even when it hurts! 💗",
            "Keep going, your future self will thank you! 🙏",
            "You deserve all the good things coming your way! 🎁",
            "Your strength is inspiring, even when you can't see it! 🌟"
        ]
    ],
    'happy' => [
        'emoji' => '😊',
        'name' => 'Happy',
        'color' => '#FFD93D',
        'quotes' => [
            "Your smile is contagious! Keep spreading that joy! 😄",
            "Happiness looks beautiful on you! Enjoy this moment! 🌟",
            "You're radiating positive energy! Keep shining! ✨",
            "Great things happen to happy people like you! 🎉",
            "Your happiness is a gift to everyone around you! 💝",
            "Joy is the best makeup! You're glowing! ✨",
            "Your positive vibes are changing the world! 🌍",
            "Keep smiling, it's a beautiful day because of you! 🌞",
            "Your laughter is music to the universe! 🎵",
            "Happiness is your natural state! Own it! 👑",
            "You're creating beautiful memories right now! 📸",
            "Your joy is magnetic and inspiring! 🧲",
            "Celebrate this moment, you deserve it! 🎊",
            "Your happy heart is your greatest treasure! 💛",
            "You're proof that good vibes attract good life! 🌈",
            "Keep this energy, it's transforming your reality! ⚡",
            "Your smile can light up the darkest room! 💡",
            "Happiness suits you perfectly! 👗",
            "You're living proof that life is beautiful! 🌺",
            "Your positive attitude is your superpower! 🦸",
            "This is what living your best life looks like! 🎯",
            "Your joy is creating ripples of positivity! 🌊",
            "You're an inspiration to everyone who sees you! 🌟",
            "Keep dancing through life like this! 💃",
            "Your happiness is well-deserved! 🏆",
            "You're making the world a better place! 🌎",
            "Your cheerful spirit is infectious! 🎈",
            "This is your time to shine brighter! ✨",
            "Your good mood is a blessing to others! 🙏",
            "You're creating your own sunshine! ☀️",
            "Keep spreading those positive vibes! 🎶",
            "Your happiness is the universe's gift to you! 🎁",
            "You're a walking ray of sunshine! 🌅",
            "Your joy is your strength! 💪",
            "Keep living in this beautiful moment! 🌸",
            "Your happiness journey is inspiring! 🚀",
            "You deserve every bit of this joy! 💖",
            "Your positive energy is limitless! ♾️",
            "Keep being the light you are! 🕯️",
            "Your smile is your best accessory! 💄",
            "This is what pure happiness looks like! 😍",
            "You're proof that good things happen! 🍀",
            "Your joy is contagious and beautiful! 🦋",
            "Keep celebrating life like this! 🥳",
            "Your happiness is well-earned! 🎖️",
            "You're living your dream right now! 💭",
            "Your cheerful heart is precious! 💎",
            "Keep this momentum going! 🎢",
            "Your happiness is inspiring others! 🌻",
            "You're exactly where you're meant to be! 🎯"
        ]
    ],
    'angry' => [
        'emoji' => '😠',
        'name' => 'Angry',
        'color' => '#FF6B6B',
        'quotes' => [
            "Take a deep breath. You have the power to choose peace! 🧘",
            "Your peace of mind is more valuable than proving you're right! 🕊️",
            "Anger is like drinking poison and expecting others to suffer. Let it go! 💚",
            "Channel this energy into something productive. You've got this! 💪",
            "It's okay to be upset, but don't let it control you. Stay strong! 🌟",
            "Your calm response is your greatest power! 🛡️",
            "This feeling will pass. Choose your response wisely! 🎯",
            "Breathe in peace, breathe out anger! 🌬️",
            "You're stronger than your temper! 💎",
            "Transform this fire into fuel for success! 🔥",
            "Your reaction determines your reality! 🌈",
            "Anger won't solve it, but your wisdom will! 🧠",
            "You control your emotions, not the other way around! 🎮",
            "Let it go, you deserve inner peace! 🏖️",
            "Your patience is more powerful than your anger! ⏳",
            "This too shall pass. Stay centered! 🎯",
            "Channel this intensity into positive action! ⚡",
            "Your peace is worth more than this moment! 💰",
            "Be bigger than this feeling! 🗻",
            "Respond with grace, not rage! 👑",
            "You have the power to choose differently! 🔑",
            "This situation doesn't deserve your inner peace! 🧘‍♀️",
            "Cool heads always win! 🧊",
            "Your calm is your superpower! 🦸",
            "Let karma handle it while you stay peaceful! ☯️",
            "You're better than this moment of anger! ⭐",
            "Transform your anger into art, action, or achievement! 🎨",
            "Your serenity is your victory! 🏆",
            "Take the high road, the view is better! 🏔️",
            "Anger is temporary, regret can be permanent! ⚠️",
            "You're in control of your emotions! 🎛️",
            "Let this go and reclaim your power! 💪",
            "Your peace of mind is priceless! 💎",
            "Be the calm in the chaos! 🌊",
            "This feeling doesn't define you! 🌟",
            "Choose wisdom over wrath! 📚",
            "Your inner peace is your greatest asset! 🏦",
            "Stay cool, stay powerful! 😎",
            "You're capable of choosing peace right now! 🕊️",
            "Let your actions speak louder than anger! 📢",
            "This moment doesn't deserve your energy! 🔋",
            "Your calm response will be your power move! 👊",
            "Rise above it with grace! 🦅",
            "You're too blessed to be stressed! 🙏",
            "Channel this into positive change! 🌱",
            "Your peace is worth fighting for! 🥊",
            "Be the master of your emotions! 🧙",
            "Let it go and grow! 🌳",
            "Your tranquility is your strength! 💚",
            "Choose to be peaceful, choose to win! 🏅"
        ]
    ],
    'anxious' => [
        'emoji' => '😰',
        'name' => 'Anxious',
        'color' => '#95E1D3',
        'quotes' => [
            "Breathe in courage, breathe out fear. You are safe! 🌬️",
            "Worrying won't change tomorrow, but it will steal your peace today! 🕊️",
            "You've survived 100% of your worst days. You're doing great! 💪",
            "Anxiety is a liar. You are capable and strong! ✨",
            "One step at a time. You don't have to have it all figured out! 🚶",
            "Your thoughts are not facts. You're going to be okay! 🧠",
            "This feeling is temporary. Your strength is permanent! 💎",
            "You are safe right here, right now! 🏡",
            "Take a deep breath. You've got this! 🫁",
            "Your anxiety doesn't define your future! 🌅",
            "Peace is possible for you! 🕊️",
            "You're stronger than your worries! 🦁",
            "This too shall pass. It always does! ⏰",
            "Ground yourself in this moment. You're okay! 🌍",
            "Your courage is bigger than your fear! 🛡️",
            "You've overcome anxiety before, you can do it again! 🏆",
            "Breathe. Everything is working out for you! 🌬️",
            "Your mind is powerful. Choose calming thoughts! 🧘",
            "You are not your anxiety! 🎭",
            "This feeling will pass like clouds in the sky! ☁️",
            "Focus on what you can control right now! 🎯",
            "You're doing better than you think! 📈",
            "Your peace is more important than your worries! 💚",
            "Take it moment by moment. You're okay! ⏳",
            "You are capable of handling whatever comes! 💪",
            "Your anxiety is not a prophecy! 🔮",
            "Calm is available to you right now! 🧘‍♀️",
            "You've been through tough times and made it! 🌟",
            "Trust yourself. You know what to do! 🎯",
            "Your worries don't have to control you! 🎮",
            "Breathe in peace, breathe out anxiety! 🌬️",
            "You are safe, loved, and capable! 💝",
            "This moment is all you need to handle! ⏰",
            "Your mind is creating scenarios, not realities! 🎬",
            "You have the tools to calm yourself! 🧰",
            "Focus on your breath, not your thoughts! 🫁",
            "You're going to be just fine! 🌈",
            "Your anxiety doesn't mean something is wrong! ⚠️",
            "Ground yourself. Look around. You're safe! 👀",
            "You've got this. One breath at a time! 🌬️",
            "Your calm is just a few breaths away! 😌",
            "Trust the process. Trust yourself! 🙏",
            "You don't have to be perfect! 🎯",
            "Your feelings are valid but not always accurate! 💭",
            "Peace is your birthright! 🕊️",
            "You are more resilient than you know! 🌳",
            "This anxiety will fade. Your strength won't! 💪",
            "Focus on now. This moment is manageable! ⏰",
            "You are not alone in this feeling! 🤝",
            "Calm is always available to you! 🧘"
        ]
    ],
    'excited' => [
        'emoji' => '🤩',
        'name' => 'Excited',
        'color' => '#FF9FF3',
        'quotes' => [
            "Your enthusiasm is inspiring! Ride this wave of energy! 🌊",
            "Amazing things happen to those who stay excited about life! 🎆",
            "Your excitement is the spark that lights up the world! ⚡",
            "Keep that fire burning! Great things are coming your way! 🔥",
            "Your positive energy is magnetic! Keep attracting greatness! 🧲",
            "This is your moment to shine! Go for it! ✨",
            "Your excitement is creating miracles! 🪄",
            "Channel this energy into making things happen! 💫",
            "You're unstoppable with this energy! 🚀",
            "Your enthusiasm is your secret weapon! ⚔️",
            "Keep this momentum! You're on fire! 🔥",
            "Your excitement is contagious and beautiful! 🦋",
            "This energy is your superpower! Use it! 💪",
            "You're creating magic right now! ✨",
            "Your passion is changing everything! 🌟",
            "Stay excited! The universe is responding! 🌌",
            "Your energy is attracting opportunities! 🎯",
            "This is what living fully looks like! 🎉",
            "Your enthusiasm lights up every room! 💡",
            "Keep riding this amazing wave! 🏄",
            "Your excitement is your greatest asset! 💎",
            "This is the energy of a champion! 🏆",
            "Your passion is inspiring everyone! 🌟",
            "Stay pumped! You're doing amazing! 💪",
            "Your energy is transforming your reality! 🌈",
            "This is the beginning of something great! 🌅",
            "Your excitement is pure gold! 🥇",
            "Keep this fire alive! It's powerful! 🔥",
            "Your enthusiasm is opening doors! 🚪",
            "This energy is your ticket to success! 🎫",
            "You're a force of nature right now! 🌪️",
            "Your passion is your purpose! 🎯",
            "Keep this vibe! It's incredible! ⚡",
            "Your excitement is creating possibilities! 🌟",
            "This is the energy of greatness! 👑",
            "Your enthusiasm is your fuel! ⛽",
            "Stay charged! You're electric! ⚡",
            "Your excitement is revolutionary! 🎆",
            "This energy is infectious! Share it! 🎈",
            "Your passion is your power! 💥",
            "Keep this buzz going! It's magic! ✨",
            "Your excitement is your compass! 🧭",
            "This is unstoppable energy! 🚂",
            "Your enthusiasm is your signature! ✍️",
            "Stay hyped! You're changing lives! 🌍",
            "Your excitement is legendary! 📜",
            "This energy is divine! Keep it flowing! 🌊",
            "Your passion is unmatched! 🔥",
            "Keep this excitement! It's your gift! 🎁",
            "Your energy is absolutely electric! ⚡"
        ]
    ],
    'tired' => [
        'emoji' => '😴',
        'name' => 'Tired',
        'color' => '#B4A7D6',
        'quotes' => [
            "Rest is not a luxury, it's a necessity. Take care of yourself! 💤",
            "Even superheroes need rest. You're allowed to pause! 🦸",
            "Your body is asking for what it needs. Listen to it! 🛌",
            "Recharge now, conquer later. You deserve this rest! 🔋",
            "Taking a break doesn't mean giving up. It means getting ready! ☕",
            "You can't pour from an empty cup. Fill yourself first! 🫖",
            "Rest is productive too! 🌙",
            "Your body needs rest to do great things! 💪",
            "Sleep is the best meditation! 🧘",
            "You've earned this rest! Take it guilt-free! 🛋️",
            "Tired is not weak, it's human! 💚",
            "Rest today, shine tomorrow! ✨",
            "Your exhaustion is valid! Honor it! 🕊️",
            "Even the strongest need to rest! 🏋️",
            "Recharging is part of success! 🔌",
            "You're not lazy, you're recovering! 🌱",
            "Rest is the foundation of productivity! 🏗️",
            "Your body is asking for love. Give it rest! 💝",
            "Tiredness is your body's wisdom speaking! 🧠",
            "Rest is not quitting, it's preparing! 🎯",
            "You deserve to slow down! 🐌",
            "Exhaustion means you've been giving your all! 🏆",
            "Rest deeply, you've earned it! 😴",
            "Your body is your home. Let it rest! 🏡",
            "Fatigue is a sign you need self-care! 🛁",
            "Rest is part of the journey! 🚶",
            "You're allowed to be tired! 🫂",
            "Sleep is healing magic! ✨",
            "Your rest is an investment in tomorrow! 💰",
            "Tired bodies create brilliant minds after rest! 🧠",
            "Honor your need for rest! 🙏",
            "Exhaustion is your body's red flag. Listen! 🚩",
            "Rest is radical self-care! 💚",
            "You can't run on empty. Refuel! ⛽",
            "Taking rest shows strength, not weakness! 💪",
            "Your tiredness deserves compassion! 💗",
            "Rest is the secret of all achievers! 🏅",
            "You're not falling behind, you're catching up on rest! ⏰",
            "Sleep is nature's nurse! 🌿",
            "Rest now, rise stronger! 🌅",
            "Your exhaustion is proof you've been working hard! 💼",
            "Give yourself permission to rest! ✅",
            "Rest is how you prepare for greatness! 🌟",
            "Tiredness is temporary, but rest is restorative! 🔄",
            "You deserve peaceful, guilt-free rest! 😌",
            "Rest is your superpower! 🦸‍♀️",
            "Listen to your body's wisdom! 👂",
            "Recharge your soul through rest! 🔋",
            "Exhaustion is calling for self-love! 💖",
            "Rest well, warrior. Tomorrow is another day! 🛡️"
        ]
    ],
    'confident' => [
        'emoji' => '😎',
        'name' => 'Confident',
        'color' => '#F38181',
        'quotes' => [
            "Your confidence is your superpower! Use it wisely! 💪",
            "You were born to stand out! Keep owning it! 👑",
            "Believe in yourself and magic happens! Keep shining! ✨",
            "You're unstoppable when you believe in yourself! 🚀",
            "Your confidence inspires others! Keep being amazing! 🌟",
            "You are powerful beyond measure! 💥",
            "Your self-belief is creating miracles! 🪄",
            "Confidence looks incredible on you! 👗",
            "You were made for greatness! 🏆",
            "Your belief in yourself is justified! ✅",
            "You're a force to be reckoned with! ⚡",
            "Your confidence is well-earned! 🥇",
            "Stand tall! You deserve every success! 📏",
            "Your self-assurance is magnetic! 🧲",
            "You're proof that confidence changes everything! 🌈",
            "Own your power! You're incredible! 💎",
            "Your confidence is your crown! Wear it! 👑",
            "You're absolutely crushing it! 🎯",
            "Your self-belief is unshakeable! 🗻",
            "You know your worth! That's powerful! 💰",
            "Your confidence is inspiring greatness! 🌟",
            "You're walking proof of what belief can do! 🚶",
            "Your self-assurance is beautiful! 💖",
            "You're a winner because you believe you are! 🏅",
            "Your confidence is changing your reality! 🌍",
            "Stand in your power! You belong here! 🏛️",
            "Your self-belief is your greatest strength! 💪",
            "You're radiating confidence and success! ☀️",
            "Your certainty in yourself is inspiring! 🎆",
            "You're unstoppable! Keep going! 🚂",
            "Your confidence is your competitive edge! ⚔️",
            "You know you're capable! Act like it! 🎬",
            "Your self-assurance is your foundation! 🏗️",
            "You're built for this! Own it! 🏋️",
            "Your confidence is transformative! 🦋",
            "You deserve every bit of your success! 🎁",
            "Your belief in yourself is powerful! ⚡",
            "You're a natural born leader! 🎖️",
            "Your confidence is electric! ⚡",
            "Stand proud! You've earned this! 🦚",
            "Your self-belief is revolutionary! 🎆",
            "You're absolutely phenomenal! 🌟",
            "Your confidence is your signature! ✍️",
            "You know your value! Show it! 💎",
            "Your self-assurance is infectious! 🦋",
            "You're a champion in every way! 🏆",
            "Your confidence is your foundation! 🏛️",
            "You're living proof of self-belief! 📸",
            "Your assurance is your advantage! 🎯",
            "You're absolutely unstoppable! 🚀"
        ]
    ],
    'grateful' => [
        'emoji' => '🙏',
        'name' => 'Grateful',
        'color' => '#FFEAA7',
        'quotes' => [
            "Gratitude turns what we have into enough! You're blessed! 💝",
            "Your grateful heart attracts more blessings! Keep counting them! 🌻",
            "Gratitude is the key to abundance. You're on the right path! 🔑",
            "Your thankful spirit makes the world brighter! Shine on! ☀️",
            "What a beautiful heart you have! Keep spreading gratitude! 💖",
            "Your appreciation is creating more to appreciate! 🌟",
            "Grateful hearts are magnetic to miracles! 🧲",
            "Your thankfulness is transforming your life! 🦋",
            "Gratitude is your gateway to happiness! 🚪",
            "Your appreciative spirit is beautiful! 🌺",
            "Thank you for being grateful! It's powerful! ⚡",
            "Your gratitude is creating abundance! 💰",
            "Keep counting blessings, not problems! 📊",
            "Your thankful heart is your treasure! 💎",
            "Gratitude is your superpower! 🦸",
            "Your appreciation changes everything! 🌍",
            "Keep that grateful energy flowing! 🌊",
            "Your thankfulness is inspiring! 🌟",
            "Gratitude is your best accessory! 👑",
            "Your appreciative spirit attracts goodness! 🍀",
            "Keep being thankful! It's magical! ✨",
            "Your grateful heart is pure gold! 🥇",
            "Appreciation is your path to joy! 🛤️",
            "Your thankfulness multiplies blessings! ✖️",
            "Gratitude looks beautiful on you! 💕",
            "Your appreciative nature is a gift! 🎁",
            "Keep thanking the universe! It listens! 👂",
            "Your grateful spirit is contagious! 🦋",
            "Thankfulness is your frequency! 📻",
            "Your gratitude is your greatest wealth! 💰",
            "Keep appreciating! More is coming! 📦",
            "Your thankful heart is wise! 🦉",
            "Gratitude is your secret to happiness! 🤫",
            "Your appreciation is creating miracles! 🪄",
            "Keep counting blessings! They're multiplying! 🔢",
            "Your grateful spirit is transformative! 🌈",
            "Thankfulness is your power move! 💪",
            "Your appreciation attracts abundance! 💸",
            "Keep being grateful! It's working! ✅",
            "Your thankful heart is precious! 💎",
            "Gratitude is your golden ticket! 🎫",
            "Your appreciative energy is powerful! ⚡",
            "Keep thanking! Keep receiving! 🎁",
            "Your grateful spirit is enlightened! 💡",
            "Appreciation is your superpower! 🦸‍♀️",
            "Your thankfulness is revolutionary! 🎆",
            "Keep that grateful vibe! It's magic! ✨",
            "Your appreciative heart is blessed! 🙏",
            "Gratitude is your path to everything! 🛤️",
            "Your thankful spirit is absolutely beautiful! 🌺"
        ]
    ],
    'lonely' => [
        'emoji' => '😔',
        'name' => 'Lonely',
        'color' => '#A8DADC',
        'quotes' => [
            "You're never truly alone. You matter more than you know! 💙",
            "This feeling is temporary. Connection is just around the corner! 🤝",
            "Your presence makes a difference, even when you can't see it! 🌟",
            "Reach out to someone. You'll be surprised how much you're valued! 💌",
            "Being alone and being lonely are different. You're worthy of love! 💕",
            "You are connected to something greater! 🌌",
            "Your existence matters to so many! 💫",
            "Loneliness is temporary, your worth is permanent! 💎",
            "You're not invisible. You're seen and valued! 👁️",
            "Connection is coming your way! 🌈",
            "You deserve companionship and love! 💝",
            "This feeling will pass. You're not forgotten! ⏰",
            "You're part of something beautiful! 🌍",
            "Your loneliness doesn't define your value! ✨",
            "Reach out! People want to hear from you! 📞",
            "You're worthy of deep connection! 🤝",
            "This isolation is temporary! 🕊️",
            "You matter more than you realize! 🌟",
            "Connection is possible for you! 🔗",
            "You're not alone in feeling alone! 🫂",
            "Your presence is a gift to others! 🎁",
            "Companionship is on its way to you! 🚶",
            "You deserve to be surrounded by love! 💖",
            "This loneliness will transform into connection! 🦋",
            "You're worthy of belonging! 🏡",
            "Someone is thinking of you right now! 💭",
            "You're more connected than you feel! 🌐",
            "Your loneliness is valid, but not your reality! 🎭",
            "Community is waiting for you! 🌍",
            "You're deserving of meaningful relationships! 💞",
            "This feeling is a chapter, not your story! 📖",
            "You're valuable beyond measure! 💰",
            "Connection is your birthright! 🎂",
            "You're never truly disconnected! 🔗",
            "Your loneliness is calling you to reach out! 📢",
            "You're worthy of deep friendships! 👥",
            "This isolation will end! 🌅",
            "You're part of the human family! 👨‍👩‍👧‍👦",
            "Your loneliness is temporary, your value eternal! ♾️",
            "Someone needs your presence too! 🤝",
            "You're connected by invisible threads of love! 🧵",
            "Companionship is seeking you! 🔍",
            "You're worthy of being chosen! ✅",
            "This feeling won't last forever! ⏳",
            "You're more loved than you know! 💗",
            "Connection is coming! Trust it! 🌈",
            "You're not meant to be alone! 🫂",
            "Your loneliness is calling for connection! 📞",
            "You're deserving of community! 🏘️",
            "You are loved, you are seen, you are valued! 💖"
        ]
    ],
    'motivated' => [
        'emoji' => '🔥',
        'name' => 'Motivated',
        'color' => '#FF7F50',
        'quotes' => [
            "This is your moment! Go out there and crush it! 💥",
            "Your determination is unstoppable! Nothing can hold you back! 🚀",
            "You're on fire! Keep that momentum going! 🔥",
            "Success is yours for the taking! Go get it, champion! 🏆",
            "Your drive inspires everyone around you! Keep pushing! 💪",
            "You're built for greatness! Show the world! 🌟",
            "This is your time to dominate! 👑",
            "Your motivation is your rocket fuel! 🚀",
            "Nothing can stop you when you're this driven! ⚡",
            "You're a force of nature! Unleash it! 🌪️",
            "Your ambition is your superpower! 💥",
            "Go harder! You're just getting started! 🏃",
            "Your determination is legendary! 📜",
            "Success is inevitable with this energy! ✅",
            "You're unstoppable! Keep charging forward! ⚡",
            "Your drive is creating your destiny! 🎯",
            "This is the energy of a champion! 🥇",
            "You're built different! Show them! 💎",
            "Your motivation is magnetic! 🧲",
            "Keep grinding! Greatness is coming! ⚙️",
            "You're in beast mode! Don't stop! 🦁",
            "Your hustle is about to pay off! 💰",
            "This is your breakthrough moment! 🌅",
            "Your determination is your destiny! 🎯",
            "You're on the path to victory! 🏁",
            "Keep this fire burning! It's powerful! 🔥",
            "Your drive is unmatched! Own it! 👊",
            "Success recognizes your energy! 📡",
            "You're making moves! Keep going! 🎬",
            "Your motivation is transforming reality! 🌈",
            "This is the attitude of winners! 🏆",
            "You're writing your success story now! ✍️",
            "Your determination is inspiring! 🌟",
            "Keep pushing! You're so close! 🎯",
            "Your drive is your competitive edge! ⚔️",
            "This is how legends are made! 📖",
            "You're creating your own destiny! 🎨",
            "Your motivation is unstoppable force! 🌊",
            "Keep grinding! It's working! ⚙️",
            "Your ambition is your blueprint! 📐",
            "This energy is pure gold! 🥇",
            "You're in the zone! Stay there! 🎯",
            "Your drive is phenomenal! 💫",
            "Success is responding to your energy! 📞",
            "You're absolutely crushing it! 💪",
            "Your determination is powerful! ⚡",
            "This is championship mentality! 🏆",
            "You're built for this moment! 🏗️",
            "Your motivation is your momentum! 🎢",
            "Keep going! You're unstoppable! 🚂"
        ]
    ]
];

// Initialize session tracking for used quotes
if (!isset($_SESSION['used_quotes'])) {
    $_SESSION['used_quotes'] = [];
}

// Handle mood selection
$selectedMood = null;
$quote = null;

if (isset($_GET['mood']) && array_key_exists($_GET['mood'], $moods)) {
    $selectedMood = $_GET['mood'];
    $moodData = $moods[$selectedMood];
    
    // Initialize array for this mood if not exists
    if (!isset($_SESSION['used_quotes'][$selectedMood])) {
        $_SESSION['used_quotes'][$selectedMood] = [];
    }
    
    // Get available quotes (not yet shown)
    $availableQuotes = array_diff(
        array_keys($moodData['quotes']),
        $_SESSION['used_quotes'][$selectedMood]
    );
    
    // If all quotes have been shown, reset
    if (empty($availableQuotes)) {
        $_SESSION['used_quotes'][$selectedMood] = [];
        $availableQuotes = array_keys($moodData['quotes']);
    }
    
    // Select a random available quote
    $quoteIndex = array_rand(array_flip($availableQuotes));
    $quote = $moodData['quotes'][$quoteIndex];
    
    // Mark this quote as used
    $_SESSION['used_quotes'][$selectedMood][] = $quoteIndex;
}
?>

    <div class="container">
        <?php if ($selectedMood): ?>
            <div class="quote-container">
                <div class="selected-mood"><?php echo $moods[$selectedMood]['emoji']; ?></div>
                <h2 style="margin-bottom: 20px;">You're feeling <?php echo $moods[$selectedMood]['name']; ?></h2>
                <div class="quote-text"><?php echo $quote; ?></div>
                <a href="index.php" class="back-btn">← Choose Another Mood</a>
            </div>
        <?php else: ?>
            <h1>How Are You Feeling Today? 💭</h1>
            <p class="subtitle">Select your current mood and get a personalized quote!</p>
            
            <div class="mood-grid">
                <?php foreach ($moods as $key => $mood): ?>
                    <a href="?mood=<?php echo $key; ?>" class="mood-card">
                        <span class="mood-emoji"><?php echo $mood['emoji']; ?></span>
                        <div class="mood-name"><?php echo $mood['name']; ?></div>
                    </a>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>

<?php include 'includes/footer.php'; ?>